# Generated by Django 2.0.2 on 2020-01-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ngo',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.CharField(default='no description provided', max_length=500)),
                ('donations', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('website', models.CharField(max_length=250)),
            ],
        ),
    ]
