# Generated by Django 2.0.2 on 2020-01-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0002_auto_20200126_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='stats',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
